#!/usr/bin/env bash
# Hear the phonological modality. The native LogOS VM synthesises the nine
# primitive phonyms — Being /ɑ/, Recognition /ʃi/, Love /lu/, Self /mɑ/,
# Relation /ʀa/, Void /hɑ/, Becoming /vu/, Form /tɑ/, Depth /dɔ/ — plus three
# phonyms GENERATED by PSC* from glyph structure (Compassion = Love⊗Recognition,
# Truth = ↻Recognition, Recognition⊂Being), writes phonyms.wav, and plays it.
#
# Unlike the DRM capstones this needs no bare VT / DRM master — audio is not an
# exclusive resource — so it runs straight from your normal session.
#
#   cd ~/logos && ./bringup_phonym.sh           # synthesise on the VM + play
#   HOST=1 ./bringup_phonym.sh                   # synthesise on the C host instead
#
# You should hear nine distinct vocal gestures, then three blended ones: the
# language speaking its own primitives, then speaking concepts built from them.
set -u
cd "$(dirname "$0")" || exit 1

echo "== building host =="
[ -x ./tiny_host ] || cc -O2 -o tiny_host tiny_host.c || { echo "tiny_host build failed"; exit 1; }

rm -f phonyms.wav
if [ "${HOST:-0}" = "1" ]; then
  echo "== synthesising phonyms.wav on the C host =="
  ./tiny_host phonym.la || { echo "host synthesis failed"; exit 1; }
else
  echo "== emitting the native VM and compiling phonym.la =="
  nasm -f bin secd.asm -o logos_secd 2>/dev/null || ./tiny_host secd.la >/dev/null 2>&1 || { echo "VM emit failed"; exit 1; }
  chmod +x logos_secd
  cp phonym.la logos_source.la
  ./tiny_host codegen.la >/dev/null 2>&1 || { echo "codegen failed"; exit 1; }
  echo "== synthesising phonyms.wav on the native VM (sovereign) =="
  ./logos_secd || { echo "VM synthesis failed"; exit 1; }
  rm -f logos_source.la logos_program.bin
fi

[ -f phonyms.wav ] || { echo "no phonyms.wav produced"; exit 1; }
echo "   wrote phonyms.wav ($(stat -c%s phonyms.wav) bytes, $(awk 'BEGIN{print (262144/2)/16000}' 2>/dev/null)s of audio)"

echo
echo "== PLAYING — nine primitive phonyms, then three generated phonyms =="
if   command -v aplay  >/dev/null 2>&1; then aplay  phonyms.wav
elif command -v paplay >/dev/null 2>&1; then paplay phonyms.wav
elif command -v ffplay >/dev/null 2>&1; then ffplay -autoexit -nodisp phonyms.wav
else echo "no aplay/paplay/ffplay found — play phonyms.wav yourself"; fi
