#!/usr/bin/env bash
# xmssidx_core.la is GENERATED by xmssidx_spec.la through specpipe's
# GENERATE -> DEPLOY. This gate asserts the committed file is what the spec
# produces TODAY — i.e. that it has not gone stale.
#
# ── WHY THIS GATE EXISTS: THE DEFECT IT WAS WRITTEN FROM ────────────────────
# On 2026-09-06 the committed xmssidx_core.la was found to differ from its own
# spec's output by one line (the `export` line). Cause: specpipe gained export
# emission in 9112c18 (2026-08-27); that commit was NOT an ancestor of track-e
# when b6a361f committed xmssidx_core.la on 2026-08-28, and reached the branch
# only via merge 1962037 on 2026-09-05. The module had been stale ever since.
#
# ★ NOTHING CAUGHT IT, AND THE REASON IS THE POINT. build.sh never runs
# xmssidx_spec.la, so the module is never regenerated during a build (unlike
# primitives.la / canon.la / psc.la, which build.sh regenerates in place and
# which therefore cannot drift). And `gate_xmssidx.sh` — the gate that LOOKS
# like it covers this file — does not read it at all: it exercises xmssidx.la,
# xmssidx_resume.la and xmssidx_exhaust.la, each of which RE-DECLARES its own
# IDX_* glyphs rather than importing the generated module. This was measured,
# not assumed: with xmssidx_core.la overwritten by a line of non-Lingua-Adamica
# garbage, gate_xmssidx.sh still exits 0 with zero FAIL lines. That is a
# Door-iii check — one that cannot fail on this artifact because it never
# executes against it. This gate is the one that does.
#
# ── HOW IT CHECKS: REGENERATE ELSEWHERE, THEN COMPARE ───────────────────────
# The spec is re-run in an ISOLATED temp dir, never in the tree. That direction
# matters: build.sh's in-place regeneration makes drift impossible by ERASING
# it, which is fine for a module nobody has hand-touched but cannot REPORT that
# a committed file was wrong. Comparing instead of overwriting is what turns
# staleness into a red line rather than a silent repair.
#
# ── ★ THE RED PATH IS EXERCISED ON EVERY RUN ───────────────────────────────
# A gate never seen red is not a gate. Arm 2 corrupts a copy of the freshly
# generated source and asserts the comparison REPORTS it. Without that, a
# comparison that had silently degenerated (an empty file compared against an
# empty file, a cmp whose exit status was discarded) would report PASS forever.
set -uo pipefail
cd "$(dirname "$0")"
ok=1

SPEC="xmssidx_spec.la"
MOD="xmssidx_core.la"

# A missing input is a broken checkout, not a configuration. Never SKIP.
for f in "$SPEC" "$MOD" specpipe.la tiny_host; do
    [ -e "$f" ] || { echo "FAIL  xmssidx_core: $f absent — a missing input is a broken checkout, not a reason to skip"; exit 1; }
done

TMP="$(mktemp -d)" || { echo "FAIL  xmssidx_core: mktemp failed"; exit 1; }
trap 'rm -rf "$TMP"' EXIT

cp ./*.la "$TMP"/ 2>/dev/null
cp ./tiny_host "$TMP"/ 2>/dev/null
rm -f "$TMP/xmssidx_spec.state"

# ── 1. the committed module is what the spec generates ──────────────────────
GENOUT="$(cd "$TMP" && timeout 300 ./tiny_host "$SPEC" 2>&1)"
case "$GENOUT" in
    *"RESULT: module VERIFIED"*) ;;
    *) echo "FAIL  xmssidx_core: the spec did not deploy VERIFIED: [$(printf '%s' "$GENOUT" | tail -3)]"; ok=0 ;;
esac

if [ -f "$TMP/$MOD" ]; then
    if ! cmp -s "$TMP/$MOD" "$MOD"; then
        echo "FAIL  xmssidx_core: the committed $MOD is NOT what $SPEC generates — it is stale or hand-edited. Regenerate it (./tiny_host $SPEC) and commit the result; never hand-edit a generated module. Diff:"
        diff "$MOD" "$TMP/$MOD" | head -10
        ok=0
    fi
else
    echo "FAIL  xmssidx_core: the spec run produced no $MOD"; ok=0
fi

# ── 2. ★ RED PATH: the comparison must be able to FAIL ──────────────────────
# Corrupt a copy of the generated source and assert the same cmp reports it.
# If this arm ever goes quiet, arm 1's green means nothing.
if [ -f "$TMP/$MOD" ]; then
    printf 'glyph MUTANT = la x. x\n' >> "$TMP/$MOD"
    if cmp -s "$TMP/$MOD" "$MOD"; then
        echo "FAIL  xmssidx_core: RED PATH DEAD — a mutated generated source still compared equal to the committed module, so arm 1 cannot fail and its PASS proves nothing"
        ok=0
    fi
fi

[ "$ok" -eq 1 ] && echo "PASS  xmssidx_core: the committed generated module is byte-identical to what xmssidx_spec.la deploys today (VERIFIED, and the comparison was shown able to fail on a mutated source in the same run). This is the check that was missing when the module sat stale from 2026-08-28 to 2026-09-06: build.sh never regenerates it, and gate_xmssidx.sh does not read it at all — that gate stays green with this file replaced by garbage, because its three drivers re-declare their own IDX_* glyphs instead of importing the generated one."
[ "$ok" -eq 1 ]
