# -*- coding: utf-8 -*-
"""Directive 3 (Erik, 2026-09-18): "The branch count swings between 28, 36, and 38. Stop enumerating and derive. The operations
are addition, merge, and recursion. Given the current inventory and these operations, the count should be a theorem."

The operations are LA's own: addition = ⊕ (co-presence), merge = ⊗ (synthesis), recursion = ↻ (self-application), with NORMK's
declared equivalences (lacore.normk: ⊕ sorted, ⊗ ordered and idempotent for ∃ alone, ↻↻→↻, ↻(BEING)→SELF — the last in the
TRUTH register only under Erik's F4 ruling (c); rewrite_being=False models the FORM register).
The inventory is branchgenesis.la's, READ from the file: 18 base branches, each (name, interface glyph ⊂(RELATION,x),
registers read), plus Δ_B's own branch G_DB = ▷(RECOGNITION,↻(RELATION)).

It computes, and prints, four things:
  (1) THE CLOSURE IS INFINITE — merge is idempotent only for ∃, so x, ⊗(x,x), ⊗(x,⊗(x,x)), … are NORMK-distinct (their tree
      sizes 1, 3, 5, … strictly grow and NORMK keeps size except at ∃/↻↻/↻BEING). Shown on every branch interface to depth 4.
      ⇒ "the count under the operations" is not a finite number. A finite count can only be a RANK: the size of the minimal
      generating set — exactly the codex's own audit criterion (App B, :4294: 47 mapped, 19 "derivations or sub-interfaces",
      28 "the necessary and sufficient set").
  (2) RANK OF THE BRANCH GLYPHS — every branch glyph has head ⊂ (▷ for Δ_B); ⊕/⊗/↻ never produce a ⊂ or ▷ head, so no branch
      glyph is generated by the others: the set is FREE, rank = size, BY CONSTRUCTION (says nothing).
  (3) RANK OF THE INTERFACES x — a branch is DERIVED iff its x is generated from the OTHER branches' x by ⊕/⊗/↻ (searched to
      tree size |x|+2, three rounds). Both registers. Uniqueness is CHECKED: the irreducibles alone must regenerate every derived
      branch (then they are the unique minimal generating set).
  (4) RANK OF THE REGISTER-SETS under union (addition read as union of domains) — the union-irreducible sets (unique).
  usage: python3 derive/branchrank.py        exit 0 (a report); 2 if the inventory cannot be read
"""
import os, re, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lacore import P, SYN, CON, DIR, CONT, MC, normk, canon, tsize
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "branchgenesis.la")   # a path argument feeds a MUTANT inventory
src = open(SRC, encoding="utf-8").read()

def die(m): print("ERROR: " + m); sys.exit(2)
def parse(e):
    """Px("N") | MC(e) | SYN/CON/DIR/CONT(e)(e) — the constructor syntax branchgenesis.la writes"""
    e = e.strip(); pos = [0]
    def ws():
        while pos[0] < len(e) and e[pos[0]] == " ": pos[0] += 1
    def arg():
        ws()
        if e[pos[0]] != "(": die("expected ( in %r" % e)
        pos[0] += 1; t = term(); ws()
        if e[pos[0]] != ")": die("expected ) in %r" % e)
        pos[0] += 1; return t
    def term():
        ws(); m = re.match(r'Px\("([A-Z]+)"\)', e[pos[0]:])
        if m: pos[0] += m.end(); return P(m.group(1))
        m = re.match(r'(MC|SYN|CONT|CON|DIR)', e[pos[0]:])   # CONT before CON: longest first
        if not m: die("cannot parse %r at %d" % (e, pos[0]))
        pos[0] += m.end(); k = m.group(1)
        if k == "MC": return MC(arg())
        a = arg(); b = arg(); return {"SYN": SYN, "CON": CON, "DIR": DIR, "CONT": CONT}[k](a, b)
    t = term(); ws()
    if pos[0] != len(e): die("trailing text in %r" % e)
    return t

rows = re.findall(r'CONSc\(BRANCH\("([a-z]+)"\)\s*\(BG\((.*?)\)\)\s*\(NL\d((?:\("[a-z]+"\))+)\)\)\(', src)
if len(rows) != 18: die("expected the 18 base branches in BASE_BRANCHES, read %d" % len(rows))
inv = [(n, parse(x), re.findall(r'"([a-z]+)"', regs)) for n, x, regs in rows]
m = re.search(r'^glyph G_DB\s*=\s*SEALc\((.*)\)\s*$', src, re.M)
if not m: die("G_DB not found")
gdb = parse(m.group(1))
m = re.search(r'^glyph C_DB\s*=.*?NL3\("([a-z]+)"\)\("([a-z]+)"\)\("([a-z]+)"\)', src, re.M)
db_regs = list(m.groups()) if m else ["evidential", "topological", "affective"]

B = lambda x: "T" if x else "F"
print("BRANCHRANK inventory read from %s:" % os.path.basename(SRC) + " %d base branches + Δ_B = %d" % (len(inv), len(inv) + 1))

# (1) the closure is infinite
def tower(x, k):
    t = x
    for _ in range(k): t = SYN(x, t)
    return t
inf_ok = all(len({normk(tower(x, k), rb) for k in range(5)}) == 5 for _, x, _ in inv for rb in (True, False))
print("BRANCHRANK (1) closure under ⊕ ⊗ ↻ is INFINITE: for every interface x, x ⊗(x,x) ⊗(x,⊗(x,x)) … are 5 NORMK-distinct forms at depth 4 (both registers):%s"
      " ⇒ a finite count can only be a RANK (a minimal generating set — the codex's own L8 audit criterion, App B :4294)" % B(inf_ok))

# (2) branch glyphs: head ⊂ (▷ for Δ_B) — never produced by ⊕ ⊗ ↻
heads = {normk(CONT(P("RELATION"), x))[0] for _, x, _ in inv} | {normk(gdb)[0]}
print("BRANCHRANK (2) branch GLYPHS: heads %s; ⊕ ⊗ ↻ never produce a ⊂ or ▷ head ⇒ no glyph is generated by the others: rank = %d = the size, BY CONSTRUCTION"
      % ("".join(sorted(heads)), len(inv) + 1))

# (3) interfaces
def generated(target, pool, rb, rounds=3):
    tgt = normk(target, rb); cap = tsize(target) + 2
    forms = {}
    for t in pool: forms.setdefault(normk(t, rb), t)
    if tgt in forms: return forms[tgt], "(equal to another branch's x)"
    for _ in range(rounds):
        items = list(forms.values()); new = {}
        for a in items:
            for c in (MC(a),): new.setdefault(normk(c, rb), c)
            for b in items:
                for c in (SYN(a, b), CON(a, b)):
                    if tsize(c) <= cap: new.setdefault(normk(c, rb), c)
        for k, v in new.items():
            if k not in forms: forms[k] = v
        if tgt in forms: return forms[tgt], ""
    return None, ""
def rank(rb):
    allx = [(n, x) for n, x, _ in inv] + [("Δ_B", DIR(P("RECOGNITION"), MC(P("RELATION"))))]
    derived = {}
    for i, (n, x) in enumerate(allx):
        others = [y for j, (_, y) in enumerate(allx) if j != i]
        w, note = generated(x, others, rb)
        if w is not None: derived[n] = (w, note)
    return allx, derived
for rb, reg in ((False, "FORM register (F4 ruling (c): ↻(BEING)≡SELF is NOT a form identity)"), (True, "TRUTH register (↻(BEING)≡SELF holds)")):
    allx, der = rank(rb)
    print("BRANCHRANK (3) interfaces x, %s: DERIVED %d — %s | rank = %d of %d"
          % (reg, len(der), "; ".join("%s = %s" % (n, canon(w)) for n, (w, _) in der.items()) or "none", len(allx) - len(der), len(allx)))
    # UNIQUENESS: an element NOT generated by all the others (irreducible) is in EVERY generating set; so if the irreducibles
    # alone regenerate every derived element, they are THE unique minimal generating set. (A chain — psycholinguistics from
    # semantics, sociolinguistics from psycholinguistics — is fine; only a cycle of mutual derivations would break this.)
    irr = [x for n, x in allx if n not in der]
    regen = {n: generated(x, irr, rb)[0] for n, x in allx if n in der}
    bad = [n for n, w in regen.items() if w is None]
    print("BRANCHRANK     the %d irreducibles alone regenerate every derived branch (the minimal generating set is UNIQUE):%s%s"
          % (len(irr), B(not bad), "" if not bad else " — NOT regenerated: " + ", ".join(bad)))

# (4) register-sets under union
sets = [(n, frozenset(r)) for n, _, r in inv] + [("Δ_B", frozenset(db_regs))]
def union_derived(i):
    n, s = sets[i]; subs = [t for j, (_, t) in enumerate(sets) if j != i and t < s]
    return subs and frozenset().union(*subs) == s
der4 = [sets[i][0] for i in range(len(sets)) if union_derived(i)]
print("BRANCHRANK (4) register-sets under union (addition = union of domains): union-REDUCIBLE %d — %s | rank = %d of %d"
      % (len(der4), ", ".join(der4), len(sets) - len(der4), len(sets)))
print("BRANCHRANK (5) the codex's 28 / 36 / 38: its branch formulas are prose (∃ ∩ Structure, Threshold(Threshold) …), not forms; the 47-list"
      " and the derivation relation of its L8 audit are not in the corpus; Tier 6 is declared OPEN (\"new branches emerge\") ⇒ NOT derivable")
