# -*- coding: utf-8 -*-
"""F20 derivation, gate §47 (numderive). From the DOCUMENTED definitions, never from a run of numderive.la:
primitives.la's VOID = λa.λb.b (zero), BECOMING = λn.λf.λx.f(n f x) (successor), BEING = λself.self — each READ BACK
from primitives.la and transcribed below as a Python closure (same call-by-value behaviour on these terms); the Church
decode n(λk.k+1)(0); the κ parts by lacore (NORMK per canon_spec.la's rules, TSIZE = unfolded node count).
Covers every pinned `nd` token, including the F26 correction's TRUTH register (the FORM register is `lf`, derived by
derive/lamform.py, a normalizer — not by this file)."""
import os, sys; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lacore import *
T = "nd"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
prim = open(os.path.join(ROOT, "primitives.la"), encoding="utf-8").read()
SRC = {"VOID": "glyph VOID = la a. la b. b", "BECOMING": "glyph BECOMING = la n. la f. la x. f(n(f)(x))", "BEING": "glyph BEING = la self. self"}
for k, line in SRC.items():                       # the transcription below is of THESE lines; if they moved, stop
    if line not in prim: print("NOTE %s primitives.la no longer has [%s] — the transcription is stale" % (T, line)); sys.exit(1)
ZERO = lambda a: lambda b: b
SUCC = lambda n: lambda f: lambda x: f(n(f)(x))
BEING = lambda s: s
tonum = lambda n: n(lambda k: k + 1)(0)
def nth(k): return ZERO if k == 0 else SUCC(nth(k - 1))
cited = SRC["VOID"] in prim and SRC["BECOMING"] in prim
seq = "".join("%d " % tonum(nth(k)) for k in range(6))
print("WANT %s NUMDERIVE (1) zero=VOID, successor=BECOMING, both read back from primitives.la:%s | numerals GENERATED by iterating the successor on zero: %s— decode correctly 0..5:%s"
      % (T, B(cited), seq, B(all(tonum(nth(k)) == k for k in range(6)))))
ONE = SUCC(ZERO)
print("WANT %s one = BECOMING(VOID) decodes to 1:%s" % (T, B(tonum(ONE) == 1)))
BAR = lambda s: s + "|"
nb, no = tonum(BEING), tonum(ONE)
eb, eo = BEING(BAR)("a"), ONE(BAR)("a")
print("WANT %s EQUAL IN TRUTH: BEING decoded as a numeral:%d one decoded:%d equal:%s | applied to (s ↦ s|) and a — BEING:%s one:%s agree:%s"
      % (T, nb, no, B(nb == no), eb, eo, B(eb == eo)))
def chain(k): return KAPPA if k == 0 else SYN(chain(k - 1), chain(k - 1))
sizes = " ".join(str(tsize(chain(k))) for k in range(6)) + " "
print("WANT %s NUMDERIVE (2) the ⊗-self-collapse chain measures: %s— equals 2^(d+2)−1 at depths 0..5:%s"
      % (T, sizes, B(all(tsize(chain(k)) == 2 ** (k + 2) - 1 for k in range(6)))))
probes = [SYN(P("BEING"), P("VOID")), CON(P("BEING"), P("VOID")), DIR(P("BEING"), P("VOID")), CONT(P("BEING"), P("VOID"))]
ks = [normk(p) for p in probes]
distinct = len(set(ks)) == 4
onesize = all(tsize(p) == 3 for p in probes)
print("WANT %s ⊗(BEING,VOID) ⊕(BEING,VOID) ▷(BEING,VOID) ⊂(BEING,VOID) are pairwise κ-DISTINCT:%s yet all four measure %d — four forms, ONE numeral:%s"
      % (T, B(distinct), tsize(probes[0]), B(distinct and onesize)))
def nform(n): return P("BEING") if n == 0 else CONT(P("BEING"), nform(n - 1))
nseal = [normk(nform(tsize(p))) for p in probes]
allsame, alldiff = len(set(nseal)) == 1, len(set(ks)) == 4
print("WANT %s THE BLINDNESS IS INHERITED — a glyph built from the NUMERAL alone collapses all four probes to ONE:%s while the κ-seal of the same four keeps them FOUR:%s → the loss is the NUMERAL's, not the sealing's:%s"
      % (T, B(allsame), B(alldiff), B(allsame and alldiff)))
print("NOTE %s the EQUAL-IN-TRUTH line is extensional on ONE probe plus the numeral decode — it does not claim βη-equality; that is lf (lamform.py)" % T)
